name: storm_forecast
channels:
  - conda-forge
dependencies:
  - flake8
  - scipy
  - numpy
  - pandas>=0.21
  - jupyter
  - matplotlib
  - scikit-learn>=0.19
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
